### PR TITLE
feat: adds mixpanel publish metrics

### PR DESCRIPTION
**Pull request by EmiiFont**
https://mixpanel.com/

@hassy 
this adds metrics to be uploaded to mixpanel

### CODE REVIEW

**Comment by hassy** [comment]
Nice, thank you for the PR and welcome to the Artillery contributor club! 😄

I've a small suggestion/question - would it make sense for the config option to be `token` or `projectToken` to be more consistent with Mixpanel's terminology (in the UI and in the example here: https://www.npmjs.com/package/mixpanel)

That aside, this look great! looking forward to shipping it! 🚢

**Comment by EmiiFont** [comment]
Thank you for the welcome😃 and for the feedback, using the project token makes so much sense.

**Comment by hassy** [comment]
Woop, merged! Thank you!

Got a little something for you here, take a look! https://s536n5kkxfx.typeform.com/to/RCcFf4Rv 👾

**Comment by EmiiFont** [comment]
@hassy how can this be released to npm?

**Comment by hassy** [comment]
v1.4.0 is out on npm now!

**Pull request merged**
