### PR TITLE
Send metrics by default

### PR DESCRIPTION
**Pull request by bobpozun**
Send metrics by default.

### CODE REVIEW

**Comment by hassy** [comment]
hi @bobpozun, thank you for the PR & apologies for the delay. `send` only affects whether [Datadog events](https://docs.datadoghq.com/events/) are created or not, all metrics should be sent by default already.

**Comment by bobpozun** [comment]
No problem! I agree and couldn't come up with a case where I'd configure datadog but not want to send events. It was a bit confusing and hard to debug so I requested that it sends them by default.

**Comment by hassy** [comment]
🙈 time flies!

**Comment by hassy** [comment]
thank you @bobpozun!

**Pull request merged**
